# Site settings
name: 技术改变生活
email: 3301308609@qq.com
author: Hang
url: http://www.tianhangyu.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/YogurtGun/
baseurl: ""
description: 学习技术，思考技术
meta_description: Hang;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yogurtgun

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
